### PR TITLE
Refactoring components and styles

### PR DESCRIPTION
**Pull request by azhry**
Changelog:
- Moving components to atoms directory (later can be arranged more properly based on its hierarchy)
- Changing CSS to SCSS and refactor the styles with component-scoped SCSS, selector level syntax, and mixins
- Removing `gatsby-plugins-react-head`
- Adding `gatsby-plugins-react-helmet` and `react-helmet`
- Creating `SEO` component using `react-helmet`, `useStaticQuery`, and `graphql`
- Adding `lang="id"` to html tag
- Adding lazyload image using `lazysizes`
- Adding `prop-types` for component prop types checking
- Hosting team images to [Cloudinary](https://cloudinary.com/)

### CODE REVIEW

**Comment by Misbahudin04** [comment]
image
background-color should be white #ffffff

**Comment by Misbahudin04** [comment]
image
missing white-box on visi misi

**Comment by Misbahudin04** [comment]
image
give a margin on white-box to fit the icon sponsor

please refer to this design https://www.figma.com/file/uaiuRP2SSywzXqvIrQ2HYh/patal_web?node-id=37%3A100

**Comment by Misbahudin04** [comment]
image
put margin on property white-box to match the icon sponsor

please refer to this design https://www.figma.com/file/uaiuRP2SSywzXqvIrQ2HYh/patal_web?node-id=37%3A100

**Comment by Misbahudin04** [comment]
"scroll down" on mobile view  and nav " ACARA TENTANG KONTAK" is not working

**Comment by azhry** [comment]
> image
> put margin on property white-box to match the icon sponsor
> 
> please refer to this design https://www.figma.com/file/uaiuRP2SSywzXqvIrQ2HYh/patal_web?node-id=37%3A100

thank you, these will be fixed asap

**Pull request merged**
